
all: make-png-cluster-arch make-png-node-arch

make-png-cluster-arch:
	inkscape -f ./cluster_architecture.pdf -e cluster_architecture.png -d 300
	
make-png-node-arch:
	inkscape -f ./node_architecture.pdf -e node_architecture.png -d 300
